# -*- coding: utf-8 -*-
"""ML-project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1asTAYefgMSzbyg_veMow1fpoXym_2eis

# importing the dataset
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv('/content/student-mat.csv', sep=";")

print(df.head())

"""# Trimming the data"""

df = df[["G1", "G2", "G3"]]
print(df.head())

"""# Seperate the data"""

import numpy as np
X = np.array(df.drop(["G3"], 1))
y = np.array(df["G3"])

"""# Splitting the data into train set and test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

print(X_train)

print(X_test)

print(y_train)

print(y_test)

"""# Implement the algorithm (Linear regression)"""

import sklearn
from sklearn import linear_model
linear = linear_model.LinearRegression()

linear.fit(X_train, y_train)
accuracy = linear.score(X_test, y_test)

print(accuracy)

"""# Predicting on specific student"""

preds = linear.predict(X_test)

for x in range(len(preds)):
  print(preds[x], X_test[x], y_test[x])